/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.SanduicheDAO;
import gui.CadastrarSanduiche;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ModelTable;
import modelo.Usuario;

/**
 *
 * @author aluno
 */
public class TelaSanduiches extends javax.swing.JFrame {

     private Usuario objUsuario;
    private SanduicheDAO sanDAO;
    private ModelTable objmodeltable;
    private boolean PesquisarSanduiches = false;
    /**
     * Creates new form TelaSanduiches
     */
    public TelaSanduiches() {
        initComponents();
        setResizable(false);
    setLocationRelativeTo(null);
   this.setLocationRelativeTo(null);
   listarValoresProdutos();
    }

    public void carregarTable(Usuario objUsuario) {

        sanDAO = new SanduicheDAO();
        ArrayList dados = new ArrayList();
        if (PesquisarSanduiches) {
            dados = sanDAO.PesquisarSanduiches();
        } else {
            objUsuario = new Usuario();
            dados = sanDAO.listarTodos();
        }
        String[] colunas = objmodeltable.getColunas();

        ModelTable modelo = new ModelTable(dados, colunas);

        tbTabelaCardápio.setModel(modelo);
        tbTabelaCardápio.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbTabelaCardápio.getColumnModel().getColumn(0).setResizable(false);
        tbTabelaCardápio.getColumnModel().getColumn(1).setPreferredWidth(120);
        tbTabelaCardápio.getColumnModel().getColumn(1).setResizable(false);
        tbTabelaCardápio.getColumnModel().getColumn(2).setPreferredWidth(250);
        tbTabelaCardápio.getColumnModel().getColumn(2).setResizable(false);
        tbTabelaCardápio.getTableHeader().setReorderingAllowed(false);
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelaCardápio = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTabelaCardápio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Ingredientes", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTabelaCardápio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelaCardápioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabelaCardápio);
        if (tbTabelaCardápio.getColumnModel().getColumnCount() > 0) {
            tbTabelaCardápio.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jButton3.setText("Atualizar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        jButton4.setText("Remover");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/telas FastBurguer (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(203, 60));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sanduba-removebg-preview (4).png"))); // NOI18N
        jMenu1.setText("Cardápio");

        jMenuItem4.setText("Menu Principal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Carrinho-removebg-preview.png"))); // NOI18N
        jMenu2.setText("Carrinho");

        jMenuItem3.setText("Carrinho");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
new TelaCarrinho().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
new UsuarioGUI().setVisible(true);
this.dispose()
        ;// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new CadastrarSanduiche().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbTabelaCardápioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelaCardápioMouseClicked
listarValoresProdutos();
      
      
// TODO add your handling code here:
    }//GEN-LAST:event_tbTabelaCardápioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSanduiches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSanduiches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSanduiches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSanduiches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSanduiches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabelaCardápio;
    // End of variables declaration//GEN-END:variables

    public void listarValoresProdutos() {
        try {
            SanduicheDAO Objsanduichedao = new SanduicheDAO();

            DefaultTableModel model = (DefaultTableModel) tbTabelaCardápio.getModel();
            model.setNumRows(0);

            ArrayList<modelo.Usuario> lista = Objsanduichedao.PesquisarSanduiches();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                   
                    lista.get(num).getNome(),
                    lista.get(num).getIngredientes(),
                    lista.get(num).getValor(),});
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores Sanduiches VIEW: " + erro);
        }

    }

}
