/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author hugol
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabelcardapio = new javax.swing.JLabel();
        jLabelcarrinho = new javax.swing.JLabel();
        jLabelperfil = new javax.swing.JLabel();
        jLabelfotosan1 = new javax.swing.JLabel();
        jLabelsanduiche1 = new javax.swing.JLabel();
        jLabelingredientes1 = new javax.swing.JLabel();
        jLabelpreço1 = new javax.swing.JLabel();
        jLabelfotosan2 = new javax.swing.JLabel();
        jLabelsanduiche2 = new javax.swing.JLabel();
        jLabelingredientes2 = new javax.swing.JLabel();
        jLabelpreço2 = new javax.swing.JLabel();
        jLabelfotosan3 = new javax.swing.JLabel();
        jLabelsanduiche3 = new javax.swing.JLabel();
        jLabelingredientes3 = new javax.swing.JLabel();
        jLabelpreço3 = new javax.swing.JLabel();
        jLabelfotosan4 = new javax.swing.JLabel();
        jLabelsanduiche4 = new javax.swing.JLabel();
        jLabelingredientes4 = new javax.swing.JLabel();
        jLabelpreço4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelcardapio.setText("Cardápio");

        jLabelcarrinho.setText("Carrinho");

        jLabelperfil.setText("Perfil");

        jLabelfotosan1.setText("imagem_sanduiche");
        jLabelfotosan1.setMaximumSize(new java.awt.Dimension(394, 217));
        jLabelfotosan1.setMinimumSize(new java.awt.Dimension(394, 217));

        jLabelsanduiche1.setText("Sanduiche");

        jLabelingredientes1.setText("Ingredientes");

        jLabelpreço1.setText("Preço");

        jLabelfotosan2.setText("imagem_sanduiche");
        jLabelfotosan2.setMaximumSize(new java.awt.Dimension(394, 217));
        jLabelfotosan2.setMinimumSize(new java.awt.Dimension(394, 217));

        jLabelsanduiche2.setText("Sanduiche");

        jLabelingredientes2.setText("Ingredientes");

        jLabelpreço2.setText("Preço");

        jLabelfotosan3.setText("imagem_sanduiche");
        jLabelfotosan3.setMaximumSize(new java.awt.Dimension(394, 217));
        jLabelfotosan3.setMinimumSize(new java.awt.Dimension(394, 217));

        jLabelsanduiche3.setText("Sanduiche");

        jLabelingredientes3.setText("Ingredientes");

        jLabelpreço3.setText("Preço");

        jLabelfotosan4.setText("imagem_sanduiche");
        jLabelfotosan4.setMaximumSize(new java.awt.Dimension(394, 217));
        jLabelfotosan4.setMinimumSize(new java.awt.Dimension(394, 217));

        jLabelsanduiche4.setText("Sanduiche");

        jLabelingredientes4.setText("Ingredientes");

        jLabelpreço4.setText("Preço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelfotosan1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelingredientes1)
                                    .addComponent(jLabelsanduiche1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelpreço1)
                                .addGap(62, 62, 62)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelcardapio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jLabelcarrinho)
                        .addGap(174, 174, 174)
                        .addComponent(jLabelperfil)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelfotosan2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelingredientes2)
                                            .addComponent(jLabelsanduiche2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelpreço2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelfotosan3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelingredientes3)
                                            .addComponent(jLabelsanduiche3)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelpreço3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelfotosan4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelingredientes4)
                                    .addComponent(jLabelsanduiche4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelpreço4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcardapio)
                    .addComponent(jLabelcarrinho)
                    .addComponent(jLabelperfil))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelsanduiche1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelingredientes1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelfotosan1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreço1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelsanduiche2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelingredientes2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelfotosan2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreço2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelsanduiche3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelingredientes3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelfotosan3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreço3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelsanduiche4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelingredientes4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelfotosan4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreço4))))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(579, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelcardapio;
    private javax.swing.JLabel jLabelcarrinho;
    private javax.swing.JLabel jLabelfotosan1;
    private javax.swing.JLabel jLabelfotosan2;
    private javax.swing.JLabel jLabelfotosan3;
    private javax.swing.JLabel jLabelfotosan4;
    private javax.swing.JLabel jLabelingredientes1;
    private javax.swing.JLabel jLabelingredientes2;
    private javax.swing.JLabel jLabelingredientes3;
    private javax.swing.JLabel jLabelingredientes4;
    private javax.swing.JLabel jLabelperfil;
    private javax.swing.JLabel jLabelpreço1;
    private javax.swing.JLabel jLabelpreço2;
    private javax.swing.JLabel jLabelpreço3;
    private javax.swing.JLabel jLabelpreço4;
    private javax.swing.JLabel jLabelsanduiche1;
    private javax.swing.JLabel jLabelsanduiche2;
    private javax.swing.JLabel jLabelsanduiche3;
    private javax.swing.JLabel jLabelsanduiche4;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
